apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      version: "0.13.5"
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: infra
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
