{{- if .Values.rbac }}
{{- if .Values.rbac.cluster }}
{{- range .Values.rbac.cluster.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azkaban:crb-${{ .role }}
subjects:
{{ toYaml .subjects | indent 2 }}
roleRef:
  kind: ClusterRole
  name: {{ .role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
