apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-config
  namespace: metallb-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-origin
    namespace: flux-system
  path: ./infra/metallb-config/clusters/all
  prune: true
  wait: true
  timeout: 5m
