apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      chart: ./infra/metallb-config/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-origin
        namespace: flux-system
  interval: 5m
  timeout: 10m
