apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
spec:
  chart:
    spec:
      chart: ./infra/metallb-config/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-origin
        namespace: flux-system
  dependsOn:
   - name: metallb
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
