# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 192.168.58.240-192.168.58.250
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: pool-advertisement
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - first-pool
