default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-json
        exclude: \/templates\/.*$
      - id: check-yaml
        exclude: \/templates\/.*$
        args:
          - --multi
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: helm
        name: Validate Helm charts
        language: docker_image
        entry: --entrypoint ./hack/validate-helm-chart.py midiparse/azkaban-ci:latest
        files: \/chart\/.*$
        pass_filenames: true
        require_serial: true
      - id: helm-docs
        name: Regenerate Helm docs
        language: docker_image
        entry: --entrypoint ./hack/regenerate-helm-doc.py midiparse/azkaban-ci:latest
        files: \/chart\/.*$
        pass_filenames: true
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
