apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ns-control
  namespace: default
spec:
  chart:
    spec:
      chart: ./admin/ns-control/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-origin
        namespace: flux-system
  interval: 1m
  timeout: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
