apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-origin
    namespace: flux-system
  path: ./infra/clusters/all
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: admin
