apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      version: ">=v1.8.1 <2.0.0"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: infra
  interval: 5m
  timeout: 10m
