apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ns-control
  namespace: default
spec:
  values:
    namespaces:
      infra: {}
      cert-manager: {}
      fluent-bit: {}
      metallb-system: {}
      contour: {}
