apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
spec:
  chart:
    spec:
      version: "9.1.2"
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
