apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  chart:
    spec:
      version: "0.20.x"
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: infra
  interval: 5m
  timeout: 10m
