apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: opa-constraints
  namespace: opa-gatekeeper-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-origin
    namespace: flux-system
  path: ./infra/opa-constraints/clusters/all
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: opa-constraint-templates
