apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPodBadImageTag
metadata:
  name: k8spodbadimagetag
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters: {}
